### ISSUE TITLE
Using TwilioMiddleware

### ISSUE THREAD

**Issue by neowashumanizedcode** [twilio/frontline-demo-service#3]
I've made the changes recommended in test to our service and get an error trying to load the customer list using the CRM callback
If I remove twilioWebhookMiddleware from "module.exports = router => {" I get Unprocessable Entity using NGROK as below.

Do I need to choose to "Upgrade callbacks" before testing these changes?

POST /callbacks/crm            403 Forbidden                                                                            POST /callbacks/crm            422 Unprocessable Entity                                                                 POST /callbacks/crm            422 Unprocessable Entity                                                                 POST /callbacks/crm            422 Unprocessable Entity                                                                 POST /callbacks/crm            403 Forbidden                                                                            POST /callbacks/crm            403 Forbidden                                                                            POST /callbacks/crm            403 Forbidden                                                                            POST /callbacks/crm            403 Forbidden                                                                            POST /callbacks/crm            403 Forbidden                                                                            POST /callbacks/crm            403 Forbidden

**Comment by askel4dd** [comment]
@neowashumanizedcode Yes, correct. You would need to upgrade callbacks to version 2 first, and only then you can test it

**Comment by neowashumanizedcode** [comment]
Now upgraded and successfully deployed - confirmed its working
